import cn from "classnames";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Logo } from "../components/icons/Logo";
import "./globals.css";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(roboto.className, "relative flex flex-grow flex-col")}
      >
        <header className="absolute inset-x-0 z-10 pt-9">
          <div className="container flex flex-row content-center items-center justify-between">
            <div className="h-6 w-40">
              <a href="">
                <Logo />
              </a>
            </div>
            <nav className="flex flex-row items-center gap-10">
              <h2 className="sr-only">Main navigation</h2>
              <a href="">Головна</a>
              <a href="">Про нас</a>
              <a href="#contacts">Контакти</a>
              <a
                href="#contacts"
                className="block rounded-xl bg-primary p-3 text-white"
              >
                Зв&apos;язатися
              </a>
            </nav>
          </div>
        </header>
        {children}
        <footer className="bg-primary py-12">
          <div className="container flex flex-col items-center">
            <div className="mb-9 h-12 w-80">
              <a href="">
                <Logo />
              </a>
            </div>
            <nav className="flex gap-10 text-t16">
              <h2 className="sr-only">Auxillary navigation</h2>
              <a>Головна</a>
              <a>Про нас</a>
              <a>Контакти</a>
              <a>Звʼязатися</a>
            </nav>
          </div>
        </footer>
      </body>
    </html>
  );
}
